var questions = [{
    "question": "Commonly used data types DO NOT include:"
    "option1": "Strings"
    "option2": "Booleans"
    "option3": "Alerts"
    "option4": "Numbers"
    "answer": "3"
}, {
    "question": "The condition in an if/else statement is enclosed within _____."
    "option1": "Quotes"
    "option2": "Curly Brackets"
    "option3": "Parantheses"
    "option4": "Square Brackets"
    "answer" : "3"
}, {
    "question": "Arrays in JavaScript can be used to store ____."
    "option1": "Strings"
    "option2": "Booleans"
    "option3": "Alerts"
    "option4": "Numbers"
    "answer" : "4"
}, {
    "question": "String values must be enclosed within _____ when being assigned to variables."
    "option1": "Commas"
    "option2": "Curly Brackets"
    "option3": "Quotes"
    "option4": "Parantheses"
    "answer" : "3"
},{
    "question": "A very useful tool used during development and debugging for printing content to the debugger is:"
    "option1": "JavaScript"
    "option2": "Terminal/Bash"
    "option3": "For Loops"
    "option4": "Console.log"
    "answer" : "4"
}]
